-- Migration 028: Seed students roster (Isomo Circles Class of 2026)
-- Source: "Emails and passwords - Isomo Circles Class of 2026 - Everyone" roster.
-- Each row links a student to their school's Starlink site via site name lookup.
--
-- Notes:
--  * site_id resolves by joining the source school label to the canonical
--    sites.name from migration 005. Schools with no matching site (none today)
--    fall back to NULL site_id but keep their school label.
--  * The source roster contains duplicate email addresses across schools
--    (data-entry artifacts). DISTINCT ON (email) keeps one row per email so a
--    single INSERT ... ON CONFLICT never targets the same email twice.
--  * Idempotent: re-running updates full_name/school/site_id for existing emails.

INSERT INTO students (full_name, email, school, site_id)
SELECT DISTINCT ON (s.email)
       s.full_name, s.email, s.site_name, sites.id
FROM (
  VALUES
    -- GS Remera Protestant
    ('Japhar Nshimyumuremyi','jnshimyumuremyi@icircles.rw','GS Remera Protestant'),
    ('Irene Mugabe','imugabe@icircles.rw','GS Remera Protestant'),
    ('Caleb Dufitimana','cdufitimana@icircles.rw','GS Remera Protestant'),
    ('Christian Niyonkuru','cniyonkuru@icircles.rw','GS Remera Protestant'),
    ('Aliane Manzi','amanzi@icircles.rw','GS Remera Protestant'),
    ('Dino Uwimana','duwimana@icircles.rw','GS Remera Protestant'),
    ('Claude Ndayishimiye','cndayishimiye@icircles.rw','GS Remera Protestant'),
    ('Sandrine Akimpaye','sakimpaye@icircles.rw','GS Remera Protestant'),
    ('Armand Ishimwe','ishimwearmand@icircles.rw','GS Remera Protestant'),
    ('Naome Tuyishimire','ntuyishimire@icircles.rw','GS Remera Protestant'),
    ('Olive Itangishaka','oitangishaka@icircles.rw','GS Remera Protestant'),
    ('Clement Ishimwe','ishimweclement@icircles.rw','GS Remera Protestant'),
    ('Frida Itangumugisha','fitangumugisha@icircles.rw','GS Remera Protestant'),
    ('Christian Mugabe','cmugabe@icircles.rw','GS Remera Protestant'),
    ('Diane Irakoze','iradiane@icircles.rw','GS Remera Protestant'),
    ('Belyse Bazitegekiki','bbazitegekiki@icircles.rw','GS Remera Protestant'),
    ('Iness Umukundwanase','iumukundwanase@icircles.rw','GS Remera Protestant'),
    ('Queen Akariza','qakariza@icircles.rw','GS Remera Protestant'),
    ('Justin Mugisha','mugishajustin@icircles.rw','GS Remera Protestant'),
    ('Regis Ndayishimiye','rndayishimiye@icircles.rw','GS Remera Protestant'),
    ('Olive Uwimana','uwimanaolive@icircles.rw','GS Remera Protestant'),
    ('Milliam Umurerwa','mumurerwa@icircles.rw','GS Remera Protestant'),
    ('Liliane Iradukunda','liradukunda@icircles.rw','GS Remera Protestant'),
    ('Gad Nkuzimana','gnkuzimana@icircles.rw','GS Remera Protestant'),
    ('Hyacenta Uwayo','huwayo@icircles.rw','GS Remera Protestant'),

    -- GS Remera Indangamirwa
    ('Sivan Nzinkwinkunda','snzinkwinkunda@icircles.rw','GS Remera Indangamirwa'),
    ('Claudette Bazubagira','cbazubagira@icircles.rw','GS Remera Indangamirwa'),
    ('Steven Sibomana','ssibomana@icircles.rw','GS Remera Indangamirwa'),
    ('Elise Ishimwe','ishimweelise@icircles.rw','GS Remera Indangamirwa'),
    ('Celine Uzwinimana','cuzwinimana@icircles.rw','GS Remera Indangamirwa'),
    ('Yvette Umutoniwase','yvette@icircles.rw','GS Remera Indangamirwa'),
    ('Charles Byiringiro','byiringirocharles@icircles.rw','GS Remera Indangamirwa'),
    ('Fabrice Shumbusho','fshumbusho@icircles.rw','GS Remera Indangamirwa'),
    ('Patrick Igihozo','igihozopatrick@icircles.rw','GS Remera Indangamirwa'),
    ('Joselyne Mujawayezu','jmujawayezu@icircles.rw','GS Remera Indangamirwa'),
    ('Stella Uwimpaye','suwimpaye@icircles.rw','GS Remera Indangamirwa'),
    ('Etienne Kwizera','kwizeraetienne@icircles.rw','GS Remera Indangamirwa'),
    ('Idrissa Uwineza','iuwineza@icircles.rw','GS Remera Indangamirwa'),
    ('Philomene Niyomufasha','pniyomufasha@icircles.rw','GS Remera Indangamirwa'),
    ('Paul Twizeyimana','ptwizeyimana@icircles.rw','GS Remera Indangamirwa'),
    ('Janviere Nyiranshimiyiman','jnyiranshimiyiman@icircles.rw','GS Remera Indangamirwa'),
    ('Noella Ingabire','ningabire@icircles.rw','GS Remera Indangamirwa'),
    ('Daniel Ishoborabyose','dishoborabyose@icircles.rw','GS Remera Indangamirwa'),
    ('Cedrick Shema','cshema@icircles.rw','GS Remera Indangamirwa'),
    ('Benjamin Mfitumukiza','bmfitumukiza@icircles.rw','GS Remera Indangamirwa'),
    ('Olivier Izibyose','oizibyose@icircles.rw','GS Remera Indangamirwa'),
    ('Jean Mbarushimana','mbarushimanajean@icircles.rw','GS Remera Indangamirwa'),
    ('Clementine Isingizwe','cisingizwe@icircles.rw','GS Remera Indangamirwa'),
    ('Eric Niyonzima','eniyonzima@icircles.rw','GS Remera Indangamirwa'),
    ('Saidi Bakundufite','sbakundufite@icircles.rw','GS Remera Indangamirwa'),

    -- GS Maranyundo
    ('David Munyampeta','dmunyampeta@icircles.rw','GS Maranyundo'),
    ('Gideon Sibomana','gsibomana@icircles.rw','GS Maranyundo'),
    ('Alliane Munyana','munyanaalliane@icircles.rw','GS Maranyundo'),
    ('Kenia Ikirezi','kikirezi@icircles.rw','GS Maranyundo'),
    ('Jimmy Mucyo','jmucyo@icircles.rw','GS Maranyundo'),
    ('Ange Akimfura','akimfuraange@icircles.rw','GS Maranyundo'),
    ('Yvette Umutoniwase','yumutoniwase@icircles.rw','GS Maranyundo'),
    ('Perle Burasa','pburasa@icircles.rw','GS Maranyundo'),
    ('Djafar Dusengimana','ddusengimana@icircles.rw','GS Maranyundo'),
    ('Gael Mugisha','gmugisha@icircles.rw','GS Maranyundo'),
    ('Irene Niyonkuru','iniyonkuru@icircles.rw','GS Maranyundo'),
    ('Edwin Kanyesiije','ekanyesiije@icircles.rw','GS Maranyundo'),
    ('Yves Mugisha','ymugisha@icircles.rw','GS Maranyundo'),
    ('Evra Shimwa','eshimwa@icircles.rw','GS Maranyundo'),
    ('Kevine Tuyisenge','ktuyisenge@icircles.rw','GS Maranyundo'),
    ('Sandrine Mutesi','smutesi@icircles.rw','GS Maranyundo'),
    ('Aimable Havugimana','ahavugimana@icircles.rw','GS Maranyundo'),
    ('Blessing Hirwa','hirwablessing@icircles.rw','GS Maranyundo'),
    ('Kevine Umukundwa','kumukundwa@icircles.rw','GS Maranyundo'),
    ('Emmerance Iradukunda','eiradukunda@icircles.rw','GS Maranyundo'),
    ('Prince Niyibizi','pniyibizi@icircles.rw','GS Maranyundo'),
    ('Reponse Tuyizere','tuyizerereponse@icircles.rw','GS Maranyundo'),
    ('Benitha Irakoze','birakoze@icircles.rw','GS Maranyundo'),
    ('Cedrick Sahoguteta','csahoguteta@icircles.rw','GS Maranyundo'),
    ('Valentin Dukuzimana','vdukuzimana@icircles.rw','GS Maranyundo'),

    -- GS Nyagasambu
    ('Leonce Nishimirwe','lnishimirwe@icircles.rw','GS Nyagasambu'),
    ('Nadia Bamurebe','nbamurebe@icircles.rw','GS Nyagasambu'),
    ('Tom Kagwisagye','tkagwisagye@icircles.rw','GS Nyagasambu'),
    ('Yvonne Uwanyirimpuhwe','yuwanyirimpuhwe@icircles.rw','GS Nyagasambu'),
    ('Safi Uwineza','uwinezasafi@icircles.rw','GS Nyagasambu'),
    ('Seraphine Ufitinema','sufitinema@icircles.rw','GS Nyagasambu'),
    ('Claude Irabizi','irabiziclaude@icircles.rw','GS Nyagasambu'),
    ('Moses Nsegiyumva','mnsegiyumva@icircles.rw','GS Nyagasambu'),
    ('Divine Irasubiza','dirasubiza@icircles.rw','GS Nyagasambu'),
    ('Carine Mutanganda','cmutanganda@icircles.rw','GS Nyagasambu'),
    ('Carine Uwacu','cuwacu@icircles.rw','GS Nyagasambu'),
    ('Kezia Umubyeyi','kumubyeyi@icircles.rw','GS Nyagasambu'),
    ('Zawadi Mutoni','zmutoni@icircles.rw','GS Nyagasambu'),
    ('Honorine Irasubiza','hirasubiza@icircles.rw','GS Nyagasambu'),
    ('Dieudonne Ndahimana','dndahimana@icircles.rw','GS Nyagasambu'),
    ('Sharon Mukundwa','smukundwa@icircles.rw','GS Nyagasambu'),
    ('David Kagame','dkagame@icircles.rw','GS Nyagasambu'),
    ('Peace Nakunda','pnakunda@icircles.rw','GS Nyagasambu'),
    ('Keilla Mahoro','kmahoro@icircles.rw','GS Nyagasambu'),
    ('Serapie Mukeshimana','smukeshimana@icircles.rw','GS Nyagasambu'),
    ('Esther Igihozo','eigihozo@icircles.rw','GS Nyagasambu'),
    ('Allen Kayesu','akayesu@icircles.rw','GS Nyagasambu'),
    ('Zubert Dukizimungu','zdukizimungu@icircles.rw','GS Nyagasambu'),
    ('Eric Mugisha','emugisha@icircles.rw','GS Nyagasambu'),
    ('Elisa Bizimana','ebizimana@icircles.rw','GS Nyagasambu'),
    ('Fabrice Manzi','fmanzi@icircles.rw','GS Nyagasambu'),
    ('Aimee Murengezi','amurengezi@icircles.rw','GS Nyagasambu'),
    ('Aimee Izerwa','aizerwa@icircles.rw','GS Nyagasambu'),
    ('Jean-Pierre Kayiganwa','jkayiganwa@icircles.rw','GS Nyagasambu'),
    ('Sandrine Ishimwe','sandrineishimwe@icircles.rw','GS Nyagasambu'),

    -- GS Mubuga II
    ('Liliane Gisubizo','lgisubizo@icircles.rw','GS Mubuga II'),
    ('Jean Nizeyimana','jnizeyimana@icircles.rw','GS Mubuga II'),
    ('Benitha Iragena','biragena@icircles.rw','GS Mubuga II'),
    ('Fulgence Byiringiro','fbyiringiro@icircles.rw','GS Mubuga II'),
    ('Emerance Abizera','eabizera@icircles.rw','GS Mubuga II'),
    ('Aimable Rukundo','arukundo@icircles.rw','GS Mubuga II'),
    ('Constantine Dusabemariya','cdusabemariya@icircles.rw','GS Mubuga II'),
    ('Ernest Dusingizimana','edusingizimana@icircles.rw','GS Mubuga II'),
    ('Elia Niyonsenga','eniyonsenga@icircles.rw','GS Mubuga II'),
    ('Jean Tugirimana','jtugirimana@icircles.rw','GS Mubuga II'),
    ('Hyancitha Ihimbazwe','hihimbazwe@icircles.rw','GS Mubuga II'),
    ('Christian Tuyishimire','ctuyishimire@icircles.rw','GS Mubuga II'),
    ('Clemence Isangenkundi','cisangenkundi@icircles.rw','GS Mubuga II'),
    ('Fabiola Igihozo','figihozo@icircles.rw','GS Mubuga II'),
    ('Iphigenie Ishimwe','iishimwe@icircles.rw','GS Mubuga II'),
    ('Sandrine Utamuriza','sutamuriza@icircles.rw','GS Mubuga II'),
    ('Claire Uwamahoro','uwamahoroclaire@icircles.rw','GS Mubuga II'),
    ('Provia Uwambajimana','puwambajimana@icircles.rw','GS Mubuga II'),
    ('Patience Bayisingize','pbayisingize@icircles.rw','GS Mubuga II'),
    ('Aline Nyiraneza','anyiraneza@icircles.rw','GS Mubuga II'),
    ('Albertine Uwiringiyimana','auwiringiyimana@icircles.rw','GS Mubuga II'),
    ('Pierre Kwizera','pkwizera@icircles.rw','GS Mubuga II'),

    -- GS Mubuga N (mapped to GS Mubuga II - no distinct site record)
    ('Ferdinand Dusengimana','dusengimanaferdinand@icircles.rw','GS Mubuga II'),
    ('Aimable Tumaine','atumaine@icircles.rw','GS Mubuga II'),
    ('Philippe Muneza','pmuneza@icircles.rw','GS Mubuga II'),
    ('Jean Tuyizere','tuyizerejean@icircles.rw','GS Mubuga II'),
    ('Ernestine Ukwibishaka','eukwibishaka@icircles.rw','GS Mubuga II'),
    ('Elyse Abikunda','eabikunda@icircles.rw','GS Mubuga II'),
    ('Olivier Byiringiro','obyiringiro@icircles.rw','GS Mubuga II'),
    ('Sosthene Bugingo','sbugingo@icircles.rw','GS Mubuga II'),
    ('Fred Twahirwa','ftwahirwa@icircles.rw','GS Mubuga II'),
    ('Albertine Dusingizimana','adusingizimana@icircles.rw','GS Mubuga II'),
    ('Albertine','albertine@icircles.rw','GS Mubuga II'),
    ('Simeon Dukundimana','sdukundimana@icircles.rw','GS Mubuga II'),
    ('Belyse Cyusa','pcyusa@icircles.rw','GS Mubuga II'),
    ('Jean Dufitumukiza','cdufitumukiza@icircles.rw','GS Mubuga II'),
    ('Rehema Niragire','rniragire@icircles.rw','GS Mubuga II'),
    ('Issa Rwigema','irwigema@icircles.rw','GS Mubuga II'),
    ('Betty Iradukunda','biradukunda@icircles.rw','GS Mubuga II'),
    ('Olivier Nsanzibyaremye','onsanzibyaremye@icircles.rw','GS Mubuga II'),
    ('Elie Nzabandora','enzabandora@icircles.rw','GS Mubuga II'),

    -- GS Nyange
    ('Jean Izere','jeanizere@icircles.rw','GS Nyange'),
    ('Aphrodis Cyizere','acyizere@icircles.rw','GS Nyange'),
    ('Deborah Iranejeje','diranejeje@icircles.rw','GS Nyange'),
    ('Placide Byishimimo','pbyishimimo@icircles.rw','GS Nyange'),
    ('Kevine Ingabire','kingabire@icircles.rw','GS Nyange'),
    ('Abdullah Gihozo','agihozo@icircles.rw','GS Nyange'),
    ('Egide Niyomukiza','eniyomukiza@icircles.rw','GS Nyange'),
    ('Patrick Habineza','phabineza@icircles.rw','GS Nyange'),
    ('Emmanuel Ishimwe','iemmanuel@icircles.rw','GS Nyange'),
    ('Eric Ndayishimiye','endayishimiye@icircles.rw','GS Nyange'),
    ('Natacha Irasubiza','nirasubiza@icircles.rw','GS Nyange'),
    ('Sallah Niyogushimwa','sniyogushimwa@icircles.rw','GS Nyange'),
    ('Ange Benegusenga','fbenegusenga@icircles.rw','GS Nyange'),
    ('Hycentha Irasubiza','irasubiza@icircles.rw','GS Nyange'),
    ('Olivier Munezero','omunezero@icircles.rw','GS Nyange'),
    ('Sandrine Uwase','sandrine@icircles.rw','GS Nyange'),
    ('Prosper Mugiraneza','pmugiraneza@icircles.rw','GS Nyange'),
    ('Jean Bihoyiki','dbihoyiki@icircles.rw','GS Nyange'),
    ('Claudette Byiringiro','claudette@icircles.rw','GS Nyange'),
    ('Cynthia Kuberimana','ckuberimana@icircles.rw','GS Nyange'),
    ('Patrick Tuyishimire','ptuyishimire@icircles.rw','GS Nyange'),
    ('Constatine Pfukamusenge','cpfukamusenge@icircles.rw','GS Nyange'),
    ('Henritte Dusabimana','hdusabimana@icircles.rw','GS Nyange'),
    ('Olivier Ndayisenga','ondayisenga@icircles.rw','GS Nyange'),
    ('Elenest Uwiringiyimana','euwiringiyimana@icircles.rw','GS Nyange'),

    -- St Paul Muko
    ('Gisele Mwamikazi','gmwamikazi@icircles.rw','St Paul Muko'),
    ('Obedi Maniragena','omaniragena@icircles.rw','St Paul Muko'),
    ('Pierre Murangwa','dmurangwa@icircles.rw','St Paul Muko'),
    ('Kevin Niyonkuru','kniyonkuru@icircles.rw','St Paul Muko'),
    ('Valentin Hatangimana','vhatangimana@icircles.rw','St Paul Muko'),
    ('Honore Irabaruta','hirabaruta@icircles.rw','St Paul Muko'),
    ('Valentin Niyonzima','vniyonzima@icircles.rw','St Paul Muko'),
    ('Colnel Chance','cchance@icircles.rw','St Paul Muko'),
    ('Fiacre Irankunda','firankunda@icircles.rw','St Paul Muko'),
    ('Elysee Ntacyitakoze','entacyitakoze@icircles.rw','St Paul Muko'),
    ('Seth Tinyimana','stinyimana@icircles.rw','St Paul Muko'),
    ('Claudine Ishime','cishime@icircles.rw','St Paul Muko'),
    ('Blessing Iratuzi','biratuzi@icircles.rw','St Paul Muko'),
    ('Solange Uwumukiza','suwumukiza@icircles.rw','St Paul Muko'),
    ('Vincent Hakizimana','vhakizimana@icircles.rw','St Paul Muko'),
    ('Jean Gisubizo','pgisubizo@icircles.rw','St Paul Muko'),
    ('Pierre Niyokwizera','pniyokwizera@icircles.rw','St Paul Muko'),
    ('Elie Mukeshimana','emukeshimana@icircles.rw','St Paul Muko'),
    ('Emmile Irambona','eirambona@icircles.rw','St Paul Muko'),
    ('Elisa Ishimwe','ishelisa@icircles.rw','St Paul Muko'),
    ('Samuel Bizimana','sbizimana@icircles.rw','St Paul Muko'),
    ('Japhet Tumukunde','jtumukunde@icircles.rw','St Paul Muko'),
    ('Alexis Habineza','ahabineza@icircles.rw','St Paul Muko'),
    ('Igue Irakoze','iirakoze@icircles.rw','St Paul Muko'),
    ('Donathe Nisingizwe','dnisingizwe@icircles.rw','St Paul Muko'),

    -- GS Gishyita
    ('Cindy Shimwa','fshimwa@icircles.rw','GS Gishyita'),
    ('Kevine Umurerwa','kumurerwa@icircles.rw','GS Gishyita'),
    ('Naomie Clementine','cnaomie@icircles.rw','GS Gishyita'),
    ('Valens Niyonsenga','vniyonsenga@icircles.rw','GS Gishyita'),
    ('Jean Iradukunda','jeaniradukunda@icircles.rw','GS Gishyita'),
    ('Innocent Niyigena','iniyigena@icircles.rw','GS Gishyita'),
    ('Esther Uwayisenga','euwayisenga@icircles.rw','GS Gishyita'),
    ('Jules Sibomana','jules@icircles.rw','GS Gishyita'),
    ('Clementine Ndayishimye','cndayishimye@icircles.rw','GS Gishyita'),
    ('Darada Manirakiza','dmanirakiza@icircles.rw','GS Gishyita'),
    ('Liliane Uwase','luwase@icircles.rw','GS Gishyita'),
    ('Salomon Gatoya','sgatoya@icircles.rw','GS Gishyita'),
    ('Chantal Iradukunda','chantairadukunda@icircles.rw','GS Gishyita'),
    ('Mami Imfurakazi','mimfurakazi@icircles.rw','GS Gishyita'),
    ('Ishimwe Ntawigenera','intawigenera@icircles.rw','GS Gishyita'),
    ('Adeline Niyomwungeli','aniyomwungeli@icircles.rw','GS Gishyita'),
    ('Sylvie Akimana','sakimana@icircles.rw','GS Gishyita'),
    ('Joselyne Imanishimwe','jimanishimwe@icircles.rw','GS Gishyita'),
    ('Aline Uwamahoro','auwamahoro@icircles.rw','GS Gishyita'),
    ('Farida Uwijuru','fuwijuru@icircles.rw','GS Gishyita'),
    ('Carine Umwali','cumwali@icircles.rw','GS Gishyita'),
    ('Lucky Uwineza','luwineza@icircles.rw','GS Gishyita'),
    ('Jeanine Uwiringiyimana','juwiringiyimana@icircles.rw','GS Gishyita'),
    ('Anysie Mukamana','amukamana@icircles.rw','GS Gishyita'),
    ('Placide Barasenga','pbarasenga@icircles.rw','GS Gishyita'),

    -- GS Gihara
    ('Florence Uhorasenga','fuhorasenga@icircles.rw','GS Gihara'),
    ('Emelyne Uwase','emelyneuwase@icircles.rw','GS Gihara'),
    ('Happiness Uwitonze','huwitonze@icircles.rw','GS Gihara'),
    ('Anicet Mugwiza','gmugwiza@icircles.rw','GS Gihara'),
    ('Claver Niyonsaba','cniyonsaba@icircles.rw','GS Gihara'),
    ('Jean Manirafasha','pmanirafasha@icircles.rw','GS Gihara'),
    ('Anaclet Niyitanga','aniyitanga@icircles.rw','GS Gihara'),
    ('Judith Nyiranshimiyimana','jnyiranshimiyimana@icircles.rw','GS Gihara'),
    ('Josue Niyonsimza','jniyonsimza@icircles.rw','GS Gihara'),
    ('Theofile Bikorimana','tbikorimana@icircles.rw','GS Gihara'),
    ('Diane Irakoze','irakozediane@icircles.rw','GS Gihara'),
    ('Sandrine Uwiringiyimana','suwiringiyimana@icircles.rw','GS Gihara'),
    ('Roger Ndayishimiye','rimpano@icircles.rw','GS Gihara'),
    ('Yvette Mushyimana','ymushyimana@icircles.rw','GS Gihara'),
    ('Sifa Imanishimwe','simanishimwe@icircles.rw','GS Gihara'),
    ('Fazir Irasubiza','imanishimwesifa@icircles.rw','GS Gihara'),
    ('Chanceline Ishimwe','chancelineishimwe@icircles.rw','GS Gihara'),
    ('Benitha Nishimwe','bnishimwe@icircles.rw','GS Gihara'),

    -- GS Kinigi
    ('David Niyomugabo','dniyomugabo@icircles.rw','GS Kinigi'),
    ('Patrick Usenzarasubizwa','pusenzarasubizwa@icircles.rw','GS Kinigi'),
    ('Evodie Dukuzimuremyi','edukuzimuremyi@icircles.rw','GS Kinigi'),
    ('Claude Ahishakiye','cahishakiye@icircles.rw','GS Kinigi'),
    ('Olivier Dusabimana','odusabimana@icircles.rw','GS Kinigi'),
    ('Innocent Byiringiro','innocentbyiringiro@icircles.rw','GS Kinigi'),
    ('Egide Ndikubwayo','endikubwayo@icircles.rw','GS Kinigi'),
    ('Jean Habumugisha','dhabumugisha@icircles.rw','GS Kinigi'),
    ('Patrick Manirakiza','pmanirakiza@icircles.rw','GS Kinigi'),
    ('Naome Uwingabire','nuwingabire@icircles.rw','GS Kinigi'),
    ('Claudine Uwamahoro','uwaclaudine@icircles.rw','GS Kinigi'),
    ('Obed Siborurema','osiborurema@icircles.rw','GS Kinigi'),
    ('Theogene Hagumimana','thagumimana@icircles.rw','GS Kinigi'),
    ('Josue Nishimwe','jnishimwe@icircles.rw','GS Kinigi'),
    ('Vanessa Niyizarere','vniyizarere@icircles.rw','GS Kinigi'),
    ('Emmanuel Nidufashe','enidufashe@icircles.rw','GS Kinigi'),
    ('John Irumva','jirunva@icircles.rw','GS Kinigi'),
    ('Michel Abikunda','mabikunda@icircles.rw','GS Kinigi'),
    ('Jacqueline Iransubije','jiransubije@icircles.rw','GS Kinigi'),
    ('Kennedy Munezero','kmunezero@icircles.rw','GS Kinigi'),
    ('Innocent Gihozo','igihozo@icircles.rw','GS Kinigi'),
    ('Yvan Rugendo','arugendo@icircles.rw','GS Kinigi'),
    ('Anitha Ahishakiye','aahishakiye@icircles.rw','GS Kinigi'),
    ('Anitha Uwayo','suwayo@icircles.rw','GS Kinigi'),
    ('Philemon Habumugisha','phabumugisha@icircles.rw','GS Kinigi'),

    -- Cornerstone Leadership Academy (CLA)
    ('Kenny Mudumizi','kmudumizi@icircles.rw','Cornerstone Leadership Academy'),
    ('Camella Ntiharirizwa','cntiharirizwa@icircles.rw','Cornerstone Leadership Academy'),
    ('Joyeuse Irakoze','irakozejoyeuse@icircles.rw','Cornerstone Leadership Academy'),
    ('Favour Ishimwe','favourishimwe@icircles.rw','Cornerstone Leadership Academy'),
    ('Theoneste Tunezerwe','ttunezerwe@icircles.rw','Cornerstone Leadership Academy'),
    ('Alloys Byiringiro','abyiringiro@icircles.rw','Cornerstone Leadership Academy'),
    ('Ange Agatore','bagatore@icircles.rw','Cornerstone Leadership Academy'),
    ('Rita Makambaza','rmakambaza@icircles.rw','Cornerstone Leadership Academy'),
    ('Hope Abatesi','habatesi@icircles.rw','Cornerstone Leadership Academy'),
    ('Arlette Kayirangwa','akayirangwa@icircles.rw','Cornerstone Leadership Academy'),
    ('Nadia Mutoni','nmutoni@icircles.rw','Cornerstone Leadership Academy'),
    ('Belen Beza','dbeza@icircles.rw','Cornerstone Leadership Academy'),
    ('Hope Ineza','hineza@icircles.rw','Cornerstone Leadership Academy'),
    ('Yonggi Muhirwa','cmuhirwa@icircles.rw','Cornerstone Leadership Academy'),
    ('Nelly Tunganirimana','vtunganirimana@icircles.rw','Cornerstone Leadership Academy'),
    ('Caleb Sebagangi','csebagangi@icircles.rw','Cornerstone Leadership Academy'),
    ('Erny Ntiyoberwa','dntiyoberwa@icircles.rw','Cornerstone Leadership Academy'),
    ('Kelly Sezerano','ksezerano@icircles.rw','Cornerstone Leadership Academy'),
    ('Claude Niyomungere','cniyomungere@icircles.rw','Cornerstone Leadership Academy'),
    ('Marcel Hirwa','hirwamarcel@icircles.rw','Cornerstone Leadership Academy'),
    ('Maxime Rugabirwa','mrugabirwa@icircles.rw','Cornerstone Leadership Academy'),
    ('Shelta Sezerano','msezerano@icircles.rw','Cornerstone Leadership Academy'),
    ('Hungu Ndayikengurukiye','hndayikengurukiye@icircles.rw','Cornerstone Leadership Academy'),
    ('Christella Nyampinga','cnyampinga@icircles.rw','Cornerstone Leadership Academy'),
    ('Jeff Ngoga','sngoga@icircles.rw','Cornerstone Leadership Academy'),
    ('Adeline Manishimwe','amanishimwe@icircles.rw','Cornerstone Leadership Academy'),
    ('Beni Akwira','bakwira@icircles.rw','Cornerstone Leadership Academy'),
    ('Nadine Muvunyi','nmuvunyi@icircles.rw','Cornerstone Leadership Academy'),
    ('Joel Irishura','jirishura@icircles.rw','Cornerstone Leadership Academy'),
    ('Ihozo Munyansanga','omunyansanga@icircles.rw','Cornerstone Leadership Academy'),

    -- Rwamagana Leaders (RLS)
    ('Kelly Shumbusho','kshumbusho@icircles.rw','Rwamagana Leaders'),
    ('Allen Batamuliza','abatamuliza@icircles.rw','Rwamagana Leaders'),
    ('Mukama Kefa','kmukama@icircles.rw','Rwamagana Leaders'),
    ('Bahige Barack Chris','cbarack@icircles.rw','Rwamagana Leaders'),
    ('Aurore Kamoso','akamoso@icircles.rw','Rwamagana Leaders'),
    ('Esther Shimwadewe','esthershimwadewe@icircles.rw','Rwamagana Leaders'),
    ('Kessy Deluna','dkessy@icircles.rw','Rwamagana Leaders'),
    ('Dylan Ndoba','dndoba@icircles.rw','Rwamagana Leaders'),
    ('Keza Ntwali','kezantwali@icircles.rw','Rwamagana Leaders'),
    ('David Ngoga','davidngoga@icircles.rw','Rwamagana Leaders'),
    ('Daniel Hirwa','danielhirwa@icircles.rw','Rwamagana Leaders'),
    ('Elvis Rubayiza','elvisrubayiza@icircles.rw','Rwamagana Leaders'),
    ('Gael Ganza','gganza@icircles.rw','Rwamagana Leaders'),
    ('Regis Akuzwe','akuzweregis@icircles.rw','Rwamagana Leaders'),
    ('Shalon Umumarungu','ushalon@icircles.rw','Rwamagana Leaders'),
    ('Sheja Gift Mukambiza','sgift@icircles.rw','Rwamagana Leaders'),
    ('Kevine Uwera','kuwera@icircles.rw','Rwamagana Leaders'),
    ('Akaliza Giyana','akalizagiyana@icircles.rw','Rwamagana Leaders'),

    -- ASYV
    ('Daniella Nishemezwe','anishemezwe@icircles.rw','ASYV'),
    ('Sandra Iradukunda','siradukunda@icircles.rw','ASYV'),
    ('Gabriel Gasana','ggasana@icircles.rw','ASYV'),
    ('Sifa Ibyikora','sibyikora@icircles.rw','ASYV'),
    ('Yves Turayishimiye','yturayishimiye@icircles.rw','ASYV'),
    ('Junior Gabiro','jgabiro@icircles.rw','ASYV'),
    ('Fille Niyogisubizo','fniyogisubizo@icircles.rw','ASYV'),
    ('Joseph Irakoze','josephirakoze@icircles.rw','ASYV'),
    ('Sandrine Umutesiwase','umutesiwasesandrine@icircles.rw','ASYV'),
    ('Arsene Manzi','manziarsene@icircles.rw','ASYV'),
    ('Ruth Mutesi','ruthmutesi@icircles.rw','ASYV'),
    ('Janvier Mutoni','jmutoni@icircles.rw','ASYV'),
    ('Darlene Ubwizabwimana','dubwizabwimana@icircles.rw','ASYV'),
    ('Justin Byiringiro','byiringirojustin@icircles.rw','ASYV'),
    ('Patience Uwase','uwasepatience@icircles.rw','ASYV'),
    ('Joy Nirere','jnirere@icircles.rw','ASYV'),
    ('Dieu Ndicunguye','jndicunguye@icircles.rw','ASYV'),
    ('Sandrine Uwase','uwasesandrine@icircles.rw','ASYV'),
    ('Hope Cyuzuzo','hcyuzuzo@icircles.rw','ASYV'),
    ('Annick Umutoniwase','aumutoniwase@icircles.rw','ASYV'),
    ('Antoinette Uwineza','auwineza@icircles.rw','ASYV'),
    ('Patrick Musoni','pmusoni@icircles.rw','ASYV'),
    ('Assoumpta Mukandakebuka','amukandakebuka@icircles.rw','ASYV'),
    ('Achille Muberwa','muberwaachille@icircles.rw','ASYV'),
    ('Kenny Niyonkuru','niyonkurukenny@icircles.rw','ASYV'),
    ('Solaya Ingabire','solayaingabire@icircles.rw','ASYV'),
    ('Placidia Mukeshimana','pmukeshimana@icircles.rw','ASYV'),
    ('Heritier Byiringiro','hbyiringiro@icircles.rw','ASYV'),

    -- Lycee De Zaza
    ('Joyce Kundwa','jkundwa@icircles.rw','Lycee De Zaza'),
    ('Lisah Keza','lkeza@icircles.rw','Lycee De Zaza'),
    ('Ella Kaliza','ekaliza@icircles.rw','Lycee De Zaza'),
    ('Annie Amizero','kamizero@icircles.rw','Lycee De Zaza'),
    ('Peruth Iragena','piragena@icircles.rw','Lycee De Zaza'),
    ('Honorine Manishimwe','hmanishimwe@icircles.rw','Lycee De Zaza'),
    ('Peace Mutesi','pmutesi@icircles.rw','Lycee De Zaza'),
    ('Joyce Uhiriwe','juhiriwe@icircles.rw','Lycee De Zaza'),
    ('Esther Kamikazi','ekamikazi@icircles.rw','Lycee De Zaza'),
    ('Yvette Gihozo','gihozoyvette@icircles.rw','Lycee De Zaza'),
    ('Fiacre Maombi','fmaombi@icircles.rw','Lycee De Zaza'),
    ('Gyslaine Nzayisenga','gcyuzuzo@icircles.rw','Lycee De Zaza'),
    ('Huguette Dusabeyezu','pdusabeyezu@icircles.rw','Lycee De Zaza'),
    ('Foibe Riziki','fruziki@icircles.rw','Lycee De Zaza'),
    ('Emelyne Umurerwa','eumurerwa@icircles.rw','Lycee De Zaza'),
    ('Nusura Uwase','nuwase@icircles.rw','Lycee De Zaza'),
    ('Alice Niyogisubizo','aniyogisubizo@icircles.rw','Lycee De Zaza'),
    ('Marie Uwase','louise@icircles.rw','Lycee De Zaza'),
    ('Anitha Irakoze','airakoze@icircles.rw','Lycee De Zaza'),
    ('Febronie Musabyimana','fmusabyimana@icircles.rw','Lycee De Zaza'),
    ('Kevine Iribagiza','kiribagiza@icircles.rw','Lycee De Zaza'),
    ('Chania Mutabaruka','cmutabaruka@icircles.rw','Lycee De Zaza'),
    ('Yokebedi Umutoni','yumutoni@icircles.rw','Lycee De Zaza'),
    ('Asifiwe Ingabire','asifiweingabire@icircles.rw','Lycee De Zaza'),
    ('Rosine Gihozo','rgihozo@icircles.rw','Lycee De Zaza'),

    -- ES Rusumo
    ('Edith Niyigena','eniyigena@icircles.rw','ES Rusumo'),
    ('Thierry Imanishimwe','timanishimwe@icircles.rw','ES Rusumo'),
    ('Hamza Rwibutso','hrwibutso@icircles.rw','ES Rusumo'),
    ('Jacques Mugisha','jmugisha@icircles.rw','ES Rusumo'),
    ('Pacifque Manirakoze','pmanirakoze@icircles.rw','ES Rusumo'),
    ('Sifa Mutesiwase','smutesiwase@icircles.rw','ES Rusumo'),
    ('Ange Izere','pizere@icircles.rw','ES Rusumo'),
    ('Theoneste Habumugisha','thabumugisha@icircles.rw','ES Rusumo'),
    ('Aime Munezero','smunezero@icircles.rw','ES Rusumo'),
    ('Moise Kwizera','mkwizera@icircles.rw','ES Rusumo'),
    ('Pacifique Rukundo','rukundopacifique@icircles.rw','ES Rusumo'),
    ('Sharif Ishimwe','isharif@icircles.rw','ES Rusumo'),
    ('Eline Mutoniwase','emutoniwase@icircles.rw','ES Rusumo'),
    ('Jean Niragire','bniragire@icircles.rw','ES Rusumo'),
    ('Bienvenue Uwimana','buwimana@icircles.rw','ES Rusumo'),
    ('Samuel Mugisha','smugisha@icircles.rw','ES Rusumo'),
    ('Devotha Mizero','mizerodevotha@icircles.rw','ES Rusumo'),
    ('Eric Kwizera','erickwizera@icircles.rw','ES Rusumo'),
    ('Yvette Iragena','yiragena@icircles.rw','ES Rusumo'),
    ('Samuel Ikuzwe','ikuzwesamuel@icircles.rw','ES Rusumo'),
    ('Happiness Ingabire','happinessingabire@icircles.rw','ES Rusumo'),
    ('Yannick Manzi','ymanzi@icircles.rw','ES Rusumo'),
    ('Elisa Kwizera','elisakwizera@icircles.rw','ES Rusumo'),
    ('Rene Butobwintobo','rbutobwintobo@icircles.rw','ES Rusumo'),
    ('Patrick Niyigaba','pniyigaba@icircles.rw','ES Rusumo'),

    -- Fawe Gahini (Fawe Girls)
    ('Sonia Isimbi','sisimbi@icircles.rw','Fawe Gahini'),
    ('Orion Agasaro','oagasaro@icircles.rw','Fawe Gahini'),
    ('Divine Iragena','diragena@icircles.rw','Fawe Gahini'),
    ('Sandra Gatesi','sagatesi@icircles.rw','Fawe Gahini'),
    ('Divine Uwineza','duwineza@icircles.rw','Fawe Gahini'),
    ('Ghalia Umuhire','gumuhire@icircles.rw','Fawe Gahini'),
    ('Dieu Uhiriwe','muhiriwe@icircles.rw','Fawe Gahini'),
    ('Kellen Mugisha','kkellen@icircles.rw','Fawe Gahini'),
    ('Emelyne Uwimana','euwimana@icircles.rw','Fawe Gahini'),
    ('Ines Uwera','iuwera@icircles.rw','Fawe Gahini'),
    ('Audrey Kayitavu','kayitavuaudrey@icircles.rw','Fawe Gahini'),
    ('Nadine Umukundwa','umukundwanadine@icircles.rw','Fawe Gahini'),
    ('Marie Irakoze','irakozejose@icircles.rw','Fawe Gahini'),
    ('Annah Munyana','amunyana@icircles.rw','Fawe Gahini'),
    ('Gift Akamanzi','gakamanzi@icircles.rw','Fawe Gahini'),
    ('Pearl Gasaro','pgasaro@icircles.rw','Fawe Gahini'),
    ('Kelly Mumurangungu','kmumurangungu@icircles.rw','Fawe Gahini'),
    ('Assoumpta Uwimana','auwimana@icircles.rw','Fawe Gahini'),
    ('Noella Tuyishime','ntuyishime@icircles.rw','Fawe Gahini'),
    ('Kevine Gihozo','kgihozo@icircles.rw','Fawe Gahini'),
    ('Ange Kamikazi','akamikazi@icircles.rw','Fawe Gahini'),
    ('Deborah Uwase','duwase@icircles.rw','Fawe Gahini'),
    ('Queen Muhoza','muhoza@icircles.rw','Fawe Gahini'),
    ('Marie Uwiringiyimana','marieuwiringiyimana@icircles.rw','Fawe Gahini'),
    ('Yvonne Ikimpaye','yikimpaye@icircles.rw','Fawe Gahini'),

    -- GS Muhura
    ('Pio Hirwa','phirwa@icircles.rw','GS Muhura'),
    ('Baraka Ishimwe','ibaraka@icircles.rw','GS Muhura'),
    ('Dieu Irahagije','mirahagije@icircles.rw','GS Muhura'),
    ('Fidella Bahera','fbahera@icircles.rw','GS Muhura'),
    ('Bernard Bavumiragira','bbavumiragira@icircles.rw','GS Muhura'),
    ('Chantal Tuyizere','tuyizerechantal@icircles.rw','GS Muhura'),
    ('Nelson Cyuzuzo','nelsoncyuzuzo@icircles.rw','GS Muhura'),
    ('Aurore Gatesi','agatesi@icircles.rw','GS Muhura'),
    ('Ramille Desengimana','rdesengimana@icircles.rw','GS Muhura'),
    ('Deborah Uwamahoro','duwamahoro@icircles.rw','GS Muhura'),
    ('Blaise Uwumugisha','buwumugisha@icircles.rw','GS Muhura'),
    ('Sabin Nshizirungu','snshizirungu@icircles.rw','GS Muhura'),
    ('Roi Twahirwa','eufite@icircles.rw','GS Muhura'),
    ('Rene Irakoze','irakozerene@icircles.rw','GS Muhura'),
    ('Theophilla Igiribambe','tigiribambe@icircles.rw','GS Muhura'),
    ('Eline Uwiduhaye','euwiduhaye@icircles.rw','GS Muhura'),
    ('Patrick Mugisha','pmugisha@icircles.rw','GS Muhura'),
    ('Cedrick Cyiza','ccyiza@icircles.rw','GS Muhura'),
    ('Sylvain Uwumukiza','usylvan@icircles.rw','GS Muhura'),
    ('Sierra Nisegusa','sineza@icircles.rw','GS Muhura'),
    ('Josue Sibomana','jsibomana@icircles.rw','GS Muhura'),
    ('Arstide Umuhire','aumuhire@icircles.rw','GS Muhura'),
    ('Enock Irumva','irumvaenock@icircles.rw','GS Muhura'),
    ('Jacques Nishimwe','nishimwejacques@icircles.rw','GS Muhura'),
    ('Ernest Manirakiza','manirakizaernest@icircles.rw','GS Muhura'),

    -- SOPEM Rukomo (Rukomo Sopem)
    ('Emmanuel Byiringiro','emmabyiringiro@icircles.rw','SOPEM Rukomo'),
    ('Jackson Kagabo','jkagabo@icircles.rw','SOPEM Rukomo'),
    ('Alex Byusa','abyusa@icircles.rw','SOPEM Rukomo'),
    ('Eric Niyonzima','eniyonzima2@icircles.rw','SOPEM Rukomo'),
    ('Joan Kansime','jkansime@icircles.rw','SOPEM Rukomo'),
    ('Sandrine Kayitesi','skayitesi@icircles.rw','SOPEM Rukomo'),
    ('Fiston Ntwari','fntwari@icircles.rw','SOPEM Rukomo'),
    ('Angel Umulisa','aumulisa@icircles.rw','SOPEM Rukomo'),
    ('Alex Gatsigazi','agatsigazi@icircles.rw','SOPEM Rukomo'),
    ('Cate Kashemera','ckashemera@icircles.rw','SOPEM Rukomo'),
    ('Evode Iratuzi','eiratuzi@icircles.rw','SOPEM Rukomo'),
    ('Elie Birujujwe','ebirujujwe@icircles.rw','SOPEM Rukomo'),
    ('Fred Habumugisha','fhabumugisha@icircles.rw','SOPEM Rukomo'),
    ('Aline Uhiriwe','auhiriwe@icircles.rw','SOPEM Rukomo'),
    ('Vicent Niyigaba','vniyigaba@icircles.rw','SOPEM Rukomo'),
    ('King Mugabe','kmugabe@icircles.rw','SOPEM Rukomo'),
    ('Ismael Mbayiha','imbayiha@icircles.rw','SOPEM Rukomo'),
    ('Frank Ishimwe','fishimwe@icircles.rw','SOPEM Rukomo'),
    ('Evode Manirakiza','emanirakiza@icircles.rw','SOPEM Rukomo'),
    ('Sveta Sangwa','ksangwa@icircles.rw','SOPEM Rukomo'),
    ('Sarah Ankunda','cakunda@icircles.rw','SOPEM Rukomo'),
    ('Eric Tuyishimire','etuyishimire@icircles.rw','SOPEM Rukomo'),
    ('Sandrine Gihozo','sgihozo@icircles.rw','SOPEM Rukomo'),
    ('Elisa Mwojo','emwojo@icircles.rw','SOPEM Rukomo'),
    ('Fred Ndungutse','fndungutse@icircles.rw','SOPEM Rukomo'),

    -- ES Ruhango
    ('Assia Ingabiyeneza','aingabiyeneza@icircles.rw','ES Ruhango'),
    ('Ornella Ingabire','oingabire@icircles.rw','ES Ruhango'),
    ('Ellen Shami','shamiellen@icircles.rw','ES Ruhango'),
    ('Belyse Igisubizo','bigisubizo@icircles.rw','ES Ruhango'),
    ('Peace Ineza','pineza@icircles.rw','ES Ruhango'),
    ('Gad Ngabikinze','gngabikinze@icircles.rw','ES Ruhango'),
    ('Phanette Narayisabye','pnarayisabye@icircles.rw','ES Ruhango'),
    ('Jean Shemaryayesu','jshemaryayesu@icircles.rw','ES Ruhango'),
    ('Germaine Uwiduhaye','guwiduhaye@icircles.rw','ES Ruhango'),
    ('Yannick Iranezeza','yiranezeza@icircles.rw','ES Ruhango'),
    ('Patience Irankunda','pirankunda@icircles.rw','ES Ruhango'),
    ('Damascene Nsabimana','dnsabimana@icircles.rw','ES Ruhango'),
    ('Peace Mukundenkase','mukundenkasepeace@icircles.rw','ES Ruhango'),
    ('Job Kwizera','jobkwizera@icircles.rw','ES Ruhango'),
    ('Noella Niyomwungeri','nniyomwungeri@icircles.rw','ES Ruhango'),
    ('Theonestine Uwaseneza','tuwaseneza@icircles.rw','ES Ruhango'),
    ('Jean Hakizayezu','bhakizayezu@icircles.rw','ES Ruhango'),
    ('Euler Kubwimana','rkubwimana@icircles.rw','ES Ruhango'),
    ('Regis Tuyizere','rtuyizere@icircles.rw','ES Ruhango'),
    ('Maurice Kayiranga','mkayiranga@icircles.rw','ES Ruhango'),
    ('Kelly Muhirwa','kmuhirwa@icircles.rw','ES Ruhango'),
    ('Devotha Uwizeyimana','duwizeyimana@icircles.rw','ES Ruhango'),
    ('Jmv Iradukunda','jiradukunda@icircles.rw','ES Ruhango'),
    ('Esther Uwizeyimana','euwizeyimana@icircles.rw','ES Ruhango'),
    ('Abubakari Kwizera','akwizera@icircles.rw','ES Ruhango'),

    -- Petit Seminaire St Leon (Ps St Leon Kabgayi)
    ('Arthur Hakizimana','ahakizimana@icircles.rw','Petit Seminaire St Leon'),
    ('Dylan Sebushumba','dsebushumba@icircles.rw','Petit Seminaire St Leon'),
    ('Olivier Niyomurengezi','oniyomurengezi@icircles.rw','Petit Seminaire St Leon'),
    ('Ben Ndashimye','vndashimye@icircles.rw','Petit Seminaire St Leon'),
    ('Raoul Ishimwe','rishimwe@icircles.rw','Petit Seminaire St Leon'),
    ('Norbert Kwizera','nkwizera@icircles.rw','Petit Seminaire St Leon'),
    ('Henri Ndashimye','cndashimye@icircles.rw','Petit Seminaire St Leon'),
    ('Lucky Gisingizo','pgisingizo@icircles.rw','Petit Seminaire St Leon'),
    ('Olivier Dushimimana','odushimimana@icircles.rw','Petit Seminaire St Leon'),
    ('Vincent Igiraneza','bigiraneza@icircles.rw','Petit Seminaire St Leon'),
    ('Arsene Byiringiro','byiringiroarsene@icircles.rw','Petit Seminaire St Leon'),
    ('Aldo Mugisha','mugishaaldo@icircles.rw','Petit Seminaire St Leon'),
    ('Bryan Biseruka','bineza@icircles.rw','Petit Seminaire St Leon'),
    ('Diogene Irakoze','dirakoze@icircles.rw','Petit Seminaire St Leon'),
    ('Chrispin Mpana','cmpana@icircles.rw','Petit Seminaire St Leon'),
    ('Pierre Habiyaremye','chabiyaremye@icircles.rw','Petit Seminaire St Leon'),
    ('Aldo Mutozo','amutozo@icircles.rw','Petit Seminaire St Leon'),
    ('Yannick Igiraneza','igiranezayannick@icircles.rw','Petit Seminaire St Leon'),
    ('Alain Irakoze','alainirakoze@icircles.rw','Petit Seminaire St Leon'),
    ('Samuel Maniraguha','smaniraguha@icircles.rw','Petit Seminaire St Leon'),
    ('Aulas Niyonizera','sniyonizera@icircles.rw','Petit Seminaire St Leon'),
    ('Jean Nshimiyimana','cnshimiyimana@icircles.rw','Petit Seminaire St Leon'),
    ('Christian Manishimwe','cmanishimwe@icircles.rw','Petit Seminaire St Leon'),
    ('Gaston Mugisha','gmugisha2@icircles.rw','Petit Seminaire St Leon'),

    -- CIC Muramba
    ('Nicole Ishimwe','nishimwe@icircles.rw','CIC Muramba'),
    ('Clarisse Igihozo','cigihozo@icircles.rw','CIC Muramba'),
    ('Lucky Kaneza','ckaneza@icircles.rw','CIC Muramba'),
    ('Paula Igihozo','ligihozo@icircles.rw','CIC Muramba'),
    ('Shamay Shenge','sshenge@icircles.rw','CIC Muramba'),
    ('Christella Umutoni','cumutoni@icircles.rw','CIC Muramba'),
    ('Latifa Ishimwe','lishimwe@icircles.rw','CIC Muramba'),
    ('Albine Ineza','albineza@icircles.rw','CIC Muramba'),
    ('Marie Ikuzwe','gikuzwe@icircles.rw','CIC Muramba'),
    ('Christa Iranzi','jiranzi@icircles.rw','CIC Muramba'),
    ('Alice Umutesi','aumutesi@icircles.rw','CIC Muramba'),
    ('Evelyne Cyusa','ecyusa@icircles.rw','CIC Muramba'),
    ('Prudenciene Kabatesi','pkabatesi@icircles.rw','CIC Muramba'),
    ('Rachel Mutuyimana','rmutuyimana@icircles.rw','CIC Muramba'),
    ('Floride Udahemuka','fudahemuka@icircles.rw','CIC Muramba'),
    ('Marie Umutoniwase','cumutoniwase@icircles.rw','CIC Muramba'),
    ('Marie Mutuyemariya','mmutuyemariya@icircles.rw','CIC Muramba'),
    ('Yana Iranzi','biranzi@icircles.rw','CIC Muramba'),
    ('Sifa Kwihangana','skwihangana@icircles.rw','CIC Muramba'),
    ('Micheline Irumva','mirumva@icircles.rw','CIC Muramba'),
    ('Alice Byukusenge','abyukusenge@icircles.rw','CIC Muramba'),
    ('Benitha Kizere','bkizere@icircles.rw','CIC Muramba'),
    ('Adeline Uwumukiza','auwumukiza@icircles.rw','CIC Muramba'),
    ('Nadia Niyorumuri','nniyorumuri@icircles.rw','CIC Muramba'),
    ('Honest Inema','hinema@icircles.rw','CIC Muramba'),
    ('Cezalie Gwiza','cgwiza@icircles.rw','CIC Muramba'),
    ('Laurita Igiraneza','iigiraneza@icircles.rw','CIC Muramba'),
    ('Divine Nikuze','dnikuze@icircles.rw','CIC Muramba'),
    ('Valentine Mutoni','vmutoni@icircles.rw','CIC Muramba'),

    -- ENDP (ENDPK)
    ('Sabrine Ihumure','sihumure@icircles.rw','ENDP'),
    ('Ange Igikundiro','cigikundiro@icircles.rw','ENDP'),
    ('Gloriose Umutoni','gumutoni@icircles.rw','ENDP'),
    ('Louna Gasaro','mgasaro@icircles.rw','ENDP'),
    ('Lelia Iliza','ilizalelia@icircles.rw','ENDP'),
    ('Amandine Ishimwe','amandineishimwe@icircles.rw','ENDP'),
    ('Emelyne Ishimwe','ishimwemelyne@icircles.rw','ENDP'),
    ('Latonia Ajeneza','dajeneza@icircles.rw','ENDP'),
    ('Denyse Iradukunda','diradukunda@icircles.rw','ENDP'),
    ('Rebecca Utetiwabo','rutetiwabo@icircles.rw','ENDP'),
    ('Ange Ingabire','ingabireange@icircles.rw','ENDP'),
    ('Nelly Uwase','uwasenelly@icircles.rw','ENDP'),
    ('Hervine Abayisenga','habayisenga@icircles.rw','ENDP'),
    ('Cynthia Umutoniwase','umutoniwasecynthia@icircles.rw','ENDP'),
    ('Aimee Iradukunda','iradukundaaimee@icircles.rw','ENDP'),
    ('Anathalie Uwimana','anathalieuwimana@icircles.rw','ENDP'),
    ('Redempta Uwamahoro','ruwamahoro@icircles.rw','ENDP'),
    ('Annick Nishimwe','anishimwe@icircles.rw','ENDP'),
    ('Christella Mudahunga','cmudahunga@icircles.rw','ENDP'),
    ('Divine Nkunduwera','dnkunduwera@icircles.rw','ENDP'),
    ('Naida Hirwa','nhirwa@icircles.rw','ENDP'),
    ('Marie Ishimwe','yishimwe@icircles.rw','ENDP'),
    ('Raissa Umutoniwase','umutoniwaseraissa@icircles.rw','ENDP'),
    ('Rita Habineza','habinezarita@icircles.rw','ENDP'),
    ('Lauria Gatesi','lauriagatesi@icircles.rw','ENDP'),
    ('Elisa Hategekimana','ehategekimana@icircles.rw','ENDP'),
    ('Queen Ruhatana','gruhatana@icircles.rw','ENDP'),
    ('Ella Karabo','skarabo@icircles.rw','ENDP'),
    ('Ines Uwase','iuwase@icircles.rw','ENDP'),
    ('Jovine Isano','jisano@icircles.rw','ENDP'),
    ('Merveille Ishimwe','mishimwe@icircles.rw','ENDP'),
    ('Win Niyirora','wniyirora@icircles.rw','ENDP'),
    ('Kevine Iradukunda','ikevine@icircles.rw','ENDP'),
    ('Aimee Senga','lsenga@icircles.rw','ENDP'),
    ('Annaelle Dushime','adushime@icircles.rw','ENDP'),

    -- PS St Jean Paul II
    ('Hilbert Hategekimana','hhategekimana@icircles.rw','PS St Jean Paul II'),
    ('Fidele Kwizera','fkwizera@icircles.rw','PS St Jean Paul II'),
    ('Christian Cyuzuzo','ccyuzuzo@icircles.rw','PS St Jean Paul II'),
    ('Ryan Bugingo','pbugingo@icircles.rw','PS St Jean Paul II'),
    ('Fabrice Habimana','fhabimana@icircles.rw','PS St Jean Paul II'),
    ('Marc Uwimpaye','uwimpayemarc@icircles.rw','PS St Jean Paul II'),
    ('Credo Byusa','credobyusa@icircles.rw','PS St Jean Paul II'),
    ('Simeon Sangwa','sangwasimeon@icircles.rw','PS St Jean Paul II'),
    ('Celse Ishimwe','ishimwecelse@icircles.rw','PS St Jean Paul II'),
    ('Dieudonné Ndayisenga','dndayisenga@icircles.rw','PS St Jean Paul II'),
    ('Gilbert Ndahayo','gndahayo@icircles.rw','PS St Jean Paul II'),
    ('Joseph Bizimana','jbizimana@icircles.rw','PS St Jean Paul II'),
    ('Aime Irankunda','airankunda@icircles.rw','PS St Jean Paul II'),
    ('David Adili','dadili@icircles.rw','PS St Jean Paul II'),
    ('Jean Nsengimana','nsengimanajean@icircles.rw','PS St Jean Paul II'),
    ('Anicet Irakoze','irakozeanicet@icircles.rw','PS St Jean Paul II'),
    ('Protegene Rugwiro','prugwiro@icircles.rw','PS St Jean Paul II'),
    ('Olivier Kwizera','okwizera@icircles.rw','PS St Jean Paul II'),
    ('Valentin Karamage','vkaramage@icircles.rw','PS St Jean Paul II'),
    ('Fiacre Isingizwe','fisingizwe@icircles.rw','PS St Jean Paul II'),
    ('Aimé-Patrick Cyiza','acyiza@icircles.rw','PS St Jean Paul II'),
    ('Bruce Shimwa','bshimwa@icircles.rw','PS St Jean Paul II'),
    ('Emmanuel Irasubiza','eirasubiza@icircles.rw','PS St Jean Paul II'),
    ('Théophile Niyogisubizo','tniyogisubizo@icircles.rw','PS St Jean Paul II'),
    ('Alde Dushimumukiza','cdushimumukiza@icircles.rw','PS St Jean Paul II'),

    -- GS Rambura Filles
    ('Aliane Hirwa','ahirwa@icircles.rw','GS Rambura Filles'),
    ('Kenia Niwemwiza','kniwemwiza@icircles.rw','GS Rambura Filles'),
    ('Vanessa Gatesi','vgatesi@icircles.rw','GS Rambura Filles'),
    ('Divine Keza','dkeza@icircles.rw','GS Rambura Filles'),
    ('Jennifer Mbabazi','ambabazi@icircles.rw','GS Rambura Filles'),
    ('Helvine Irakoze','hirakoze@icircles.rw','GS Rambura Filles'),
    ('Tonia Keza','kezatonia@icircles.rw','GS Rambura Filles'),
    ('Peace Hakizimana','peacehakizimana@icircles.rw','GS Rambura Filles'),
    ('Ainee Irasubiza','virasubiza@icircles.rw','GS Rambura Filles'),
    ('Nadia Uwacu','nuwacu@icircles.rw','GS Rambura Filles'),
    ('Amina Kubaho','akubaho@icircles.rw','GS Rambura Filles'),
    ('Gift Benihirwe','gbenihirwe@icircles.rw','GS Rambura Filles'),
    ('Pamella Keza','pkeza@icircles.rw','GS Rambura Filles'),
    ('Melissa Isaro','misaro@icircles.rw','GS Rambura Filles'),
    ('Alice Ineza','isaromelissa@icircles.rw','GS Rambura Filles'),
    ('Belyse Keza','bkeza@icircles.rw','GS Rambura Filles'),
    ('Fabiola Uhiriwe','fuhiriwe@icircles.rw','GS Rambura Filles'),
    ('Kelvine Izere','kizere@icircles.rw','GS Rambura Filles'),
    ('Lilian Akeza','lakeza@icircles.rw','GS Rambura Filles'),
    ('Ghoumaissa Umurerwa','gumurerwa@icircles.rw','GS Rambura Filles'),
    ('Delpine Mukeshimana','dmukeshimana@icircles.rw','GS Rambura Filles'),
    ('Esther Uwase','euwase@icircles.rw','GS Rambura Filles'),
    ('Daniella Bugingo','bugingodaniella@icircles.rw','GS Rambura Filles'),
    ('Prisca Nyiranziza','pnyiranziza@icircles.rw','GS Rambura Filles'),
    ('Jean Uwayo','juwayo@icircles.rw','GS Rambura Filles'),

    -- Lycee de St Jerome Janja
    ('White Sangano','wsangano@icircles.rw','Lycee de St Jerome Janja'),
    ('David Bimenyimana','dbimenyimana@icircles.rw','Lycee de St Jerome Janja'),
    ('Phocas Harindintwari','pharindintwari@icircles.rw','Lycee de St Jerome Janja'),
    ('Ange Ashimwe','pashimwe@icircles.rw','Lycee de St Jerome Janja'),
    ('Sonia Impundu','cimpundu@icircles.rw','Lycee de St Jerome Janja'),
    ('Gloire Uwayezu','nuwayezu@icircles.rw','Lycee de St Jerome Janja'),
    ('Happy Shimwa','shimwablaise@icircles.rw','Lycee de St Jerome Janja'),
    ('Eloi Irakoze','eirakoze@icircles.rw','Lycee de St Jerome Janja'),
    ('Emelyne Umurerwa','eumurerwa2@icircles.rw','Lycee de St Jerome Janja'),
    ('Vivine Mutuyimana','vmutuyimana@icircles.rw','Lycee de St Jerome Janja'),
    ('David Uwiringimana','duwiringimana@icircles.rw','Lycee de St Jerome Janja'),
    ('Jonathan Ishimwe','jishimwe@icircles.rw','Lycee de St Jerome Janja'),
    ('Bless Utsinze','butsinze@icircles.rw','Lycee de St Jerome Janja'),
    ('Yves Tuyishimire','ytuyishimire@icircles.rw','Lycee de St Jerome Janja'),
    ('Amelia Cyuzuzo','acyuzuzo@icircles.rw','Lycee de St Jerome Janja'),
    ('Aleluia Hundiwimpundu','ahundiwimpundu@icircles.rw','Lycee de St Jerome Janja'),
    ('Thierry Ishimwe','tishimwe@icircles.rw','Lycee de St Jerome Janja'),
    ('Aimé Bizimana','pbizimana@icircles.rw','Lycee de St Jerome Janja'),
    ('Léandre Dushimeyesu','ldushimeyesu@icircles.rw','Lycee de St Jerome Janja'),
    ('Claudette Umugwaneza','cumugwaneza@icircles.rw','Lycee de St Jerome Janja'),
    ('Alliance Ikuzo','aikuzo@icircles.rw','Lycee de St Jerome Janja'),
    ('Calvin Ineza','cineza@icircles.rw','Lycee de St Jerome Janja'),
    ('Bella Giraneza','pgiraneza@icircles.rw','Lycee de St Jerome Janja'),
    ('Ariel Igihozo','aigihozo@icircles.rw','Lycee de St Jerome Janja'),
    ('Jean Niyomungeri','bniyomungeri@icircles.rw','Lycee de St Jerome Janja'),

    -- ES Kirambo
    ('Bide Manzi','bmanzi@icircles.rw','ES Kirambo'),
    ('Jean Ikuzoryayezu','jikuzoryayezu@icircles.rw','ES Kirambo'),
    ('Rostange Irasohoza','pirasohoza@icircles.rw','ES Kirambo'),
    ('Hussein Hirwa','hhirwa@icircles.rw','ES Kirambo'),
    ('Gloria Mucyowaka','gmucyowaka@icircles.rw','ES Kirambo'),
    ('Nelson Mugisha','nmugisha@icircles.rw','ES Kirambo'),
    ('Kevin Cyuzuzo','kcyuzuzo@icircles.rw','ES Kirambo'),
    ('Samir Muganga','smuganga@icircles.rw','ES Kirambo'),
    ('Albert Mugisha','amugisha@icircles.rw','ES Kirambo'),
    ('Salvie Irasubiza','sirasubiza@icircles.rw','ES Kirambo'),
    ('Kelvin Kundwa','kkundwa@icircles.rw','ES Kirambo'),
    ('Hubert Ihirwe','gihirwe@icircles.rw','ES Kirambo'),
    ('Samuel Mugisha','mugishasam@icircles.rw','ES Kirambo'),
    ('Valentin Bonheur','vbonheur@icircles.rw','ES Kirambo'),
    ('Olivier Uwimana','ouwimana@icircles.rw','ES Kirambo'),
    ('Jean Byiringiro','cbyiringiro@icircles.rw','ES Kirambo'),
    ('Enock Izahorananatwe','eizahorananatwe@icircles.rw','ES Kirambo'),
    ('Jean Izaturinda','cizaturinda@icircles.rw','ES Kirambo'),
    ('Pacifique Irakoze','pirakoze@icircles.rw','ES Kirambo'),
    ('Soleil Abashakimana','sabashakimana@icircles.rw','ES Kirambo'),
    ('Moise Ihimbazwe','mihimbazwe@icircles.rw','ES Kirambo'),
    ('Didier Rukundo','drukundo@icircles.rw','ES Kirambo'),
    ('Honorine Iragena','hiragena@icircles.rw','ES Kirambo'),
    ('Josianne Kazeneza','jkazeneza@icircles.rw','ES Kirambo'),
    ('Jean Ndayishimiye','jndayishimiye@icircles.rw','ES Kirambo'),

    -- Inyange Girls
    ('Esther Akimanizanye','eakimanizanye@icircles.rw','Inyange Girls'),
    ('Daniella Usanase','dusanase@icircles.rw','Inyange Girls'),
    ('Peace Ishimwe','gishimwe@icircles.rw','Inyange Girls'),
    ('Ange Niyongabo','nniyongabo@icircles.rw','Inyange Girls'),
    ('Lisette Nkurunziza','lkaneza@icircles.rw','Inyange Girls'),
    ('Jany-Lay Kanyana','jkanyana@icircles.rw','Inyange Girls'),
    ('Nelsa Umwizerwa','numwizerwa@icircles.rw','Inyange Girls'),
    ('Eunice Mundere','lmundere@icircles.rw','Inyange Girls'),
    ('Délice Hirwa','mundereeunice@icircles.rw','Inyange Girls'),
    ('Delimitive Niyotwambaza','dniyotwambaza@icircles.rw','Inyange Girls'),
    ('Sandra Muneza','smuneza@icircles.rw','Inyange Girls'),
    ('Paula Ineza','inezaisimbi@icircles.rw','Inyange Girls'),
    ('Brenda Karungi','bkarungi@icircles.rw','Inyange Girls'),
    ('Fidelante Uwumuremyi','fuwumuremyi@icircles.rw','Inyange Girls'),
    ('Lydivine Turikumwe','lturikumwe@icircles.rw','Inyange Girls'),
    ('Caline Umuhoza','cumuhoza@icircles.rw','Inyange Girls'),
    ('Christa Umulisa','cumulisa@icircles.rw','Inyange Girls'),
    ('Stella Mugeni','emugeni@icircles.rw','Inyange Girls'),
    ('Renice Kamugisha','rkamugisha@icircles.rw','Inyange Girls'),
    ('Joyeuse Isimbi','jisimbi@icircles.rw','Inyange Girls'),
    ('Narada Mutambuka','nmutambuka@icircles.rw','Inyange Girls'),
    ('Ashah Beza','abeza@icircles.rw','Inyange Girls'),
    ('Caline Dukuzuwera','cdukuzuwera@icircles.rw','Inyange Girls'),
    ('Emily Isimbi','eisimbi@icircles.rw','Inyange Girls'),
    ('Neema Giramata','ogiramata@icircles.rw','Inyange Girls'),
    ('Honorine Uwizeyimana','huwizeyimana@icircles.rw','Inyange Girls'),
    ('Beline Uwajeneza','buwajeneza@icircles.rw','Inyange Girls'),
    ('Belyse Umutesi','bumutesi@icircles.rw','Inyange Girls'),
    ('Josiane Uwamahoro','juwamahoro@icircles.rw','Inyange Girls'),
    ('Ella Ikuzwe','eikuzwe@icircles.rw','Inyange Girls'),

    -- ES Mubuga II (Es Mubuga)
    ('Arstide Irankunda','ikuzweella@icircles.rw','ES Mubuga II'),
    ('Christian Kalisa','ckalisa@icircles.rw','ES Mubuga II'),
    ('Christa Ishimwe','christaishimwe@icircles.rw','ES Mubuga II'),
    ('Grade Igabe','gigabe@icircles.rw','ES Mubuga II'),
    ('Kevin Mucyo','kmucyo@icircles.rw','ES Mubuga II'),
    ('Reine Masengesho','amasengesho@icircles.rw','ES Mubuga II'),
    ('Divine Uwase','cuwase@icircles.rw','ES Mubuga II'),
    ('Sylvine Gisubizo','sgisubizo@icircles.rw','ES Mubuga II'),
    ('Deborah Ishimwe','dishimwe@icircles.rw','ES Mubuga II'),
    ('Diane Uwineza','duwineza2@icircles.rw','ES Mubuga II'),
    ('Felecien Dusengimana','fdusengimana@icircles.rw','ES Mubuga II'),
    ('Moubarak Cyomuhendo','mcyomuhendo@icircles.rw','ES Mubuga II'),
    ('Chaste Kabarisa','ckabarisa@icircles.rw','ES Mubuga II'),
    ('David Nshuti','dnshuti@icircles.rw','ES Mubuga II'),
    ('Innocent Twizerimana','itwizerimana@icircles.rw','ES Mubuga II'),
    ('Josue Dushime','jdushime@icircles.rw','ES Mubuga II'),
    ('Nadine Kabatesi','nkabatesi@icircles.rw','ES Mubuga II'),
    ('Pamella Bazamuke','pkbazamuke@icircles.rw','ES Mubuga II'),
    ('Egide Ishimwe','egideishimwe@icircles.rw','ES Mubuga II'),
    ('Believe Mucyo','bmucyo@icircles.rw','ES Mubuga II'),
    ('Abdoul Ishimwe','mucyobelieve@icircles.rw','ES Mubuga II'),
    ('Anne Ashimwe','aashimwe@icircles.rw','ES Mubuga II'),
    ('Clemence Ingabire','cingabire@icircles.rw','ES Mubuga II'),
    ('Blaise Kuzo','bkuzo@icircles.rw','ES Mubuga II'),
    ('Alliah Rusaro','rusaroalliah@icircles.rw','ES Mubuga II'),

    -- GS St Mathieu - Busasamana (St Matthieu Busasamana)
    ('Richard Ishimwe','muhirerichard@icircles.rw','GS St Mathieu - Busasamana'),
    ('Nice Munezero','nmunezero@icircles.rw','GS St Mathieu - Busasamana'),
    ('Jack Ishimwe','jishimwe2@icircles.rw','GS St Mathieu - Busasamana'),
    ('Allan Muramira','amuramira@icircles.rw','GS St Mathieu - Busasamana'),
    ('Yvan Ishimwe','muramiraallan@icircles.rw','GS St Mathieu - Busasamana'),
    ('Plaisir Ishimwe','ishimweyvan@icircles.rw','GS St Mathieu - Busasamana'),
    ('Fulgence Ishimwe','ishimweplaisir@icircles.rw','GS St Mathieu - Busasamana'),
    ('Amlan Ukuri','aukuri@icircles.rw','GS St Mathieu - Busasamana'),
    ('Amie Ufiteyesu','aufiteyesu@icircles.rw','GS St Mathieu - Busasamana'),
    ('Moise Mbonigaba','mmbonigaba@icircles.rw','GS St Mathieu - Busasamana'),
    ('Clement Umuhire','cumuhire@icircles.rw','GS St Mathieu - Busasamana'),
    ('Queen Umutesi','qumutesi@icircles.rw','GS St Mathieu - Busasamana'),
    ('Cynthia Igirimbabazi','cigirimbabazi@icircles.rw','GS St Mathieu - Busasamana'),
    ('Henriette Uwiduhaye','huwiduhaye@icircles.rw','GS St Mathieu - Busasamana'),
    ('Yvette Ishimwe','yishimwe2@icircles.rw','GS St Mathieu - Busasamana'),
    ('Mathis Basangira','gbasangira@icircles.rw','GS St Mathieu - Busasamana'),
    ('Aline Uwiduhaye','auwiduhaye@icircles.rw','GS St Mathieu - Busasamana'),
    ('Ushindi Imananiyo','uimananiyo@icircles.rw','GS St Mathieu - Busasamana'),
    ('Kizito Isezerano','kisezerano@icircles.rw','GS St Mathieu - Busasamana'),
    ('Jean Tuyisenge','ctuyisenge@icircles.rw','GS St Mathieu - Busasamana'),
    ('Joyeux Tuyiringire','jtuyiringire@icircles.rw','GS St Mathieu - Busasamana'),
    ('Fidele Irasubiza','firasubiza@icircles.rw','GS St Mathieu - Busasamana'),
    ('Innocent Hakorimana','ihakorimana@icircles.rw','GS St Mathieu - Busasamana'),
    ('Patrick Irakiza','pirakiza@icircles.rw','GS St Mathieu - Busasamana'),
    ('Pascaline Ishimwe','pishimwe@icircles.rw','GS St Mathieu - Busasamana'),

    -- ES Gisenyi
    ('Isabelle Kanyange','ikanyange@icircles.rw','ES Gisenyi'),
    ('Victoire Mugisha','vmugisha@icircles.rw','ES Gisenyi'),
    ('Eric Tuyizere','etuyizere@icircles.rw','ES Gisenyi'),
    ('Carine Isimbi','cisimbi@icircles.rw','ES Gisenyi'),
    ('Josue Byiringiro','isimbijosue@icircles.rw','ES Gisenyi'),
    ('Prince Mutangana','pmutangana@icircles.rw','ES Gisenyi'),
    ('Marie Mucyo','dmucyo@icircles.rw','ES Gisenyi'),
    ('Christian Habiyavuze','chabiyavuze@icircles.rw','ES Gisenyi'),
    ('Carine Uwamahoro','habiyavuzechristian@icircles.rw','ES Gisenyi'),
    ('Bertin Izere','bizere@icircles.rw','ES Gisenyi'),
    ('Oleba Uwajeneza','ouwajeneza@icircles.rw','ES Gisenyi'),
    ('Theogene Uwihanganye','tuwihanganye@icircles.rw','ES Gisenyi'),
    ('Ange Masengesho','amasengesho2@icircles.rw','ES Gisenyi'),
    ('Danny Hirwa','dhirwa@icircles.rw','ES Gisenyi'),
    ('Frank Niyingabo','fniyingabo@icircles.rw','ES Gisenyi'),
    ('Laban Niyokwizerwa','lniyokwizerwa@icircles.rw','ES Gisenyi'),
    ('Aline Ingabire','niyokwizerwalaban@icircles.rw','ES Gisenyi'),
    ('Theophile Hafashimana','thafashimana@icircles.rw','ES Gisenyi'),
    ('Ildephonse Ndayambaje','indayambaje@icircles.rw','ES Gisenyi'),
    ('Lisa Mboneza','lmboneza@icircles.rw','ES Gisenyi'),
    ('Rosine Irakoze','rirakoze@icircles.rw','ES Gisenyi'),
    ('Cedric Irabizi','cirabizi@icircles.rw','ES Gisenyi'),
    ('Fabrice Hirwa','fhirwa@icircles.rw','ES Gisenyi'),
    ('Joselyne Mushimiyimana','jmushimiyimana@icircles.rw','ES Gisenyi'),
    ('Theogene Asingizwe','tasingizwe@icircles.rw','ES Gisenyi'),

    -- LNDC
    ('Aurore Simbi','asimbi@icircles.rw','LNDC'),
    ('Audrey Uhagaze','auhagaze@icircles.rw','LNDC'),
    ('Anaise Keza','kezadigne@icircles.rw','LNDC'),
    ('Anabella Mutara','amutara@icircles.rw','LNDC'),
    ('Aicy Inono','tinono@icircles.rw','LNDC'),
    ('Ornella Nishimwe','onishimwe@icircles.rw','LNDC'),
    ('Parfaite Isimbi','pisimbi@icircles.rw','LNDC'),
    ('Sonia Uwase','uwase@icircles.rw','LNDC'),
    ('Raina Igena','cigena@icircles.rw','LNDC'),
    ('Marie Ingabire','singabire@icircles.rw','LNDC'),
    ('Jessica Isimbi','marebejessica@icircles.rw','LNDC'),
    ('Inyange Icyaza','iicyaza@icircles.rw','LNDC'),
    ('Josette Ukwibishaka','jukwibishaka@icircles.rw','LNDC'),
    ('Emily Igena','jigena@icircles.rw','LNDC'),
    ('Dorcas Ishimwe','ishimwedorcas@icircles.rw','LNDC'),
    ('Vaness Kirabo','vkirabo@icircles.rw','LNDC'),
    ('Vanessa Nezarwa','nnezarwa@icircles.rw','LNDC'),
    ('Anne Irumva','airumva@icircles.rw','LNDC'),
    ('Beline Ihirwe','bihirwe@icircles.rw','LNDC'),
    ('Ange Ishimwe','aishimwe@icircles.rw','LNDC'),
    ('Peace Uwase','puwase@icircles.rw','LNDC'),
    ('Merveille Uwamahoro','mkazoya@icircles.rw','LNDC'),
    ('Ange Ishimwe','angeishimwe@icircles.rw','LNDC'),
    ('Olga Ringuyeneza','oringuyeneza@icircles.rw','LNDC'),
    ('Meggi Kabera','tkabera@icircles.rw','LNDC'),

    -- ES Sancta Maria Karambo
    ('Ange Twahirwa','ktwahirwa@icircles.rw','ES Sancta Maria Karambo'),
    ('Angelo Ineza','angelosam@icircles.rw','ES Sancta Maria Karambo'),
    ('Gilbert Twiringiyimana','gtwiringiyimana@icircles.rw','ES Sancta Maria Karambo'),
    ('Remy Asifiwe','rasifiwe@icircles.rw','ES Sancta Maria Karambo'),
    ('Erneste Habiyakare','ehabiyakare@icircles.rw','ES Sancta Maria Karambo'),
    ('Christian Mucyo','cmucyo@icircles.rw','ES Sancta Maria Karambo'),
    ('Louange Maliza','lmaliza@icircles.rw','ES Sancta Maria Karambo'),
    ('Nadine Nishimwe','nnishimwe@icircles.rw','ES Sancta Maria Karambo'),
    ('Nadine Tuyizere','ntuyizere@icircles.rw','ES Sancta Maria Karambo'),
    ('Edmond Muvunyi','emuvunyi@icircles.rw','ES Sancta Maria Karambo'),
    ('Rene Kuberimana','rkuberimana@icircles.rw','ES Sancta Maria Karambo'),
    ('Jacques Byiringiro','jbyiringiro@icircles.rw','ES Sancta Maria Karambo'),
    ('Aliyasa Ndayisenga','andayisenga@icircles.rw','ES Sancta Maria Karambo'),
    ('Jean Habumugisha','phabumugisha2@icircles.rw','ES Sancta Maria Karambo'),
    ('Eric Irasubiza','irasubizaeric@icircles.rw','ES Sancta Maria Karambo'),
    ('Levis Ishimwe','hirwalevis@icircles.rw','ES Sancta Maria Karambo'),
    ('Pacifique Niyonagira','pniyonagira@icircles.rw','ES Sancta Maria Karambo'),
    ('Queen Umuganwa','kumuganwa@icircles.rw','ES Sancta Maria Karambo'),
    ('Sammy Gisubizo','mureresammy@icircles.rw','ES Sancta Maria Karambo'),
    ('Pacifique Irasubiza','pirasubiza@icircles.rw','ES Sancta Maria Karambo'),
    ('Kevin Byiringiro','kbyiringiro@icircles.rw','ES Sancta Maria Karambo'),
    ('Aime Nziza','anziza@icircles.rw','ES Sancta Maria Karambo'),
    ('Irene Byiringiro','ibyiringiro@icircles.rw','ES Sancta Maria Karambo'),
    ('Sandrine Umutoniwase','sumutoniwase@icircles.rw','ES Sancta Maria Karambo'),
    ('Donath Ibyikora','dibyikora@icircles.rw','ES Sancta Maria Karambo'),

    -- GS Notre Dame bon Conseil (Gs NDBC)
    ('Elvire Akarabo','makarabo@icircles.rw','GS Notre Dame bon Conseil'),
    ('Ange Igiraneza','kigiraneza@icircles.rw','GS Notre Dame bon Conseil'),
    ('Nice Uwineza','suwineza@icircles.rw','GS Notre Dame bon Conseil'),
    ('Yvette Uwanyirigira','duwanyirigira@icircles.rw','GS Notre Dame bon Conseil'),
    ('Neema Irakoze','irakozeneema@icircles.rw','GS Notre Dame bon Conseil'),
    ('Kevine Mutesi','kevinemutesi@icircles.rw','GS Notre Dame bon Conseil'),
    ('Gerardine Isano','gisano@icircles.rw','GS Notre Dame bon Conseil'),
    ('Ariella Mushimire','lmushimire@icircles.rw','GS Notre Dame bon Conseil'),
    ('Queen Niyonshuti','fniyonshuti@icircles.rw','GS Notre Dame bon Conseil'),
    ('Fabiola Tuyisenge','ftuyisenge@icircles.rw','GS Notre Dame bon Conseil'),
    ('Charline Munezero','cmunezero@icircles.rw','GS Notre Dame bon Conseil'),
    ('Daniella Rwabagabo','drwabagabo@icircles.rw','GS Notre Dame bon Conseil'),
    ('Peace Dushime','gdushime@icircles.rw','GS Notre Dame bon Conseil'),
    ('Blessing Usabuwera','ausabuwera@icircles.rw','GS Notre Dame bon Conseil'),
    ('Leah Kaliza','lkaliza@icircles.rw','GS Notre Dame bon Conseil'),
    ('Noella Mucyo','nmucyo@icircles.rw','GS Notre Dame bon Conseil'),
    ('Marie Irakoze','girakoze@icircles.rw','GS Notre Dame bon Conseil'),
    ('Shekinah Ihirwe','sihirwe@icircles.rw','GS Notre Dame bon Conseil'),
    ('Irene Ineza','iineza@icircles.rw','GS Notre Dame bon Conseil'),
    ('Alliance Tumukunde','atumukunde@icircles.rw','GS Notre Dame bon Conseil'),
    ('Halley Masengesho','hmasengesho@icircles.rw','GS Notre Dame bon Conseil'),
    ('Marie Manziyimana','mmanziyimana@icircles.rw','GS Notre Dame bon Conseil'),
    ('Yousra Isimbi','yisimbi@icircles.rw','GS Notre Dame bon Conseil'),
    ('Chance Irakoze','irakozechance@icircles.rw','GS Notre Dame bon Conseil'),
    ('Dynamique Uwiduhaye','suwiduhaye@icircles.rw','GS Notre Dame bon Conseil'),

    -- Maranyundo Girls School
    ('Niella Rusaro','arusaro@icircles.rw','Maranyundo Girls School'),
    ('Merveille Ihimbazwe','mihimbazwe2@icircles.rw','Maranyundo Girls School'),
    ('Angela Ishimwe','sishimwe@icircles.rw','Maranyundo Girls School'),
    ('Melissa Gasaro','mgasaro2@icircles.rw','Maranyundo Girls School'),
    ('Elsy Kayisire','ekayisire@icircles.rw','Maranyundo Girls School'),
    ('Neilla Sanga','bsanga@icircles.rw','Maranyundo Girls School'),
    ('Jenny Ineza','jineza@icircles.rw','Maranyundo Girls School'),
    ('Audrey Ineza','aineza@icircles.rw','Maranyundo Girls School'),
    ('Cedrine Ineza','bineza2@icircles.rw','Maranyundo Girls School'),
    ('Dorcas Bahati','dbahati@icircles.rw','Maranyundo Girls School'),
    ('Noella Iyakaremye','niyakaremye@icircles.rw','Maranyundo Girls School'),
    ('Sonia Isimbi','hisimbi@icircles.rw','Maranyundo Girls School'),
    ('Charmante Ntete','cntete@icircles.rw','Maranyundo Girls School'),
    ('Chartine Iradukunda','ciradukunda@icircles.rw','Maranyundo Girls School'),
    ('Rita Ineza','rineza@icircles.rw','Maranyundo Girls School'),
    ('Anitha Cyuzuzo','anithacyuzuzo@icircles.rw','Maranyundo Girls School'),
    ('Keicy Gisigo','kgisigo@icircles.rw','Maranyundo Girls School'),
    ('Divine Agasaro','dagasaro@icircles.rw','Maranyundo Girls School'),
    ('Ora Ndabikunze','andabikunze@icircles.rw','Maranyundo Girls School'),
    ('Laika Isheja','lisheja@icircles.rw','Maranyundo Girls School'),
    ('Nikita Cyuzuzo','ncyuzuzo@icircles.rw','Maranyundo Girls School'),
    ('Aniella Rujeni','arujeni@icircles.rw','Maranyundo Girls School'),
    ('Laura Abera','aabera@icircles.rw','Maranyundo Girls School'),
    ('Abigail Agasaro','aagasaro@icircles.rw','Maranyundo Girls School'),
    ('Diane Mukundwa','dmukundwa@icircles.rw','Maranyundo Girls School'),

    -- ES Juru
    ('Yves Mucyo','ymucyo@icircles.rw','ES Juru'),
    ('Pie Ndikumana','pndikumana@icircles.rw','ES Juru'),
    ('Sulaiman Rwakana','mrwakana@icircles.rw','ES Juru'),
    ('Hycentha Ingabire','hingabire@icircles.rw','ES Juru'),
    ('Godwin Niyizubwenge','gniyizubwenge@icircles.rw','ES Juru'),
    ('Stella Sugira','ssugira@icircles.rw','ES Juru'),
    ('Prince Kayiranga','pkayiranga@icircles.rw','ES Juru'),
    ('Dominique Sezerano','xsezerano@icircles.rw','ES Juru'),
    ('Patience Kamikazi','pkamiakzi@icircles.rw','ES Juru'),
    ('Trevor Kami','tkami@icircles.rw','ES Juru'),
    ('Rebecca Nishimwe','mishimwe2@icircles.rw','ES Juru'),
    ('Evra Byiringiro','ebyiringiro@icircles.rw','ES Juru'),
    ('Patrick Mucyo','pmucyo@icircles.rw','ES Juru'),
    ('Emery Kwizera','emery@icircles.rw','ES Juru'),
    ('Sankala Ganza','sganza@icircles.rw','ES Juru'),
    ('Kevin Rugwiro','krugwiro@icircles.rw','ES Juru'),
    ('Penuel Umukundwa','pumukundwa@icircles.rw','ES Juru'),
    ('Oda Ninkabandi','eninkabandi@icircles.rw','ES Juru'),
    ('Kevine Umutoniwase','kumutoniwase@icircles.rw','ES Juru'),
    ('Kevin Irumva','kirumva@icircles.rw','ES Juru'),
    ('Forever Ishimwe','fishimwe2@icircles.rw','ES Juru'),
    ('Rene Iradukunda','riradukunda@icircles.rw','ES Juru'),
    ('Solange Mushimiyimana','smushimiyimana@icircles.rw','ES Juru'),
    ('Teckla Irakoze','tirakoze@icircles.rw','ES Juru'),
    ('Josue Shimirwa','jshimirwa@icircles.rw','ES Juru'),

    -- ES Gikonko
    ('Aimable Ndarishize','andarishize@icircles.rw','ES Gikonko'),
    ('Nesta Ganza','nganza@icircles.rw','ES Gikonko'),
    ('Bella Uwase','cuwase2@icircles.rw','ES Gikonko'),
    ('Jean Ntezimana','fntezimana@icircles.rw','ES Gikonko'),
    ('Aime Gisubizo','bgisubizo@icircles.rw','ES Gikonko'),
    ('Benitha Giramata','bgiramata@icircles.rw','ES Gikonko'),
    ('Bora Ingabire','cingabire2@icircles.rw','ES Gikonko'),
    ('Remy Nizeyimana','rnizeyimana@icircles.rw','ES Gikonko'),
    ('Edwin Rugira','erugira@icircles.rw','ES Gikonko'),
    ('Princess Uwase','puwase2@icircles.rw','ES Gikonko'),
    ('Patrick Uwamahirwe','puwamahirwe@icircles.rw','ES Gikonko'),
    ('Robert Nshimiyimana','mshimiyimana@icircles.rw','ES Gikonko'),
    ('Liness Itangimbabazi','litangimbabazi@icircles.rw','ES Gikonko'),
    ('Bruce Kwizera','bkwizera@icircles.rw','ES Gikonko'),
    ('Elyse Habiyaremye','ehabiyaremye@icircles.rw','ES Gikonko'),
    ('Christian Ishimwe','cishimwe@icircles.rw','ES Gikonko'),
    ('Samuel Uwahamagawe','suwahamagawe@icircles.rw','ES Gikonko'),
    ('Wivine Ishimwe','wishimwe@icircles.rw','ES Gikonko'),
    ('Naome Ntirampeba','nntirampeba@icircles.rw','ES Gikonko'),
    ('Anitha Uwizeyimana','auwizeyimana@icircles.rw','ES Gikonko'),
    ('Evariste Ntezirembo','entezirembo@icircles.rw','ES Gikonko'),
    ('Ineza Kabayiza','lkabayiza@icircles.rw','ES Gikonko'),
    ('Jean Nsanzimana','jnsanzimana@icircles.rw','ES Gikonko'),
    ('Kenny Bugingo','kbugingo@icircles.rw','ES Gikonko'),
    ('Obed Niyonamabaza','oniyonamabaza@icircles.rw','ES Gikonko'),

    -- St Joseph Nyamasheke
    ('Samuel Twabonyimbaragazayo','tsamuel@icircles.rw','St Joseph Nyamasheke'),
    ('Parfait Cyizere','pcyizere@icircles.rw','St Joseph Nyamasheke'),
    ('Gadine Umuragwa','gumuragwa@icircles.rw','St Joseph Nyamasheke'),
    ('Dominique Nishimwe','dnishimwe@icircles.rw','St Joseph Nyamasheke'),
    ('Seraphin Iyoturikume','siyoturikume@icircles.rw','St Joseph Nyamasheke'),
    ('Samuel Itangishaka','sitangishaka@icircles.rw','St Joseph Nyamasheke'),
    ('Patience Shukuru','pshukuru@icircles.rw','St Joseph Nyamasheke'),
    ('Fabrice Ibyimanikora','fibyimanikora@icircles.rw','St Joseph Nyamasheke'),
    ('Eliakim Niyukuri','eniyukuri@icircles.rw','St Joseph Nyamasheke'),
    ('Gedeon Niyimana','gniyimana@icircles.rw','St Joseph Nyamasheke'),
    ('Placide Iyabivuze','piyabivuze@icircles.rw','St Joseph Nyamasheke'),
    ('Devothe Ishimwe','iyabivuzeplacide@icircles.rw','St Joseph Nyamasheke'),
    ('David Habamugisha','dhabamugisha@icircles.rw','St Joseph Nyamasheke'),
    ('Dieudonne Niyibizi','dniyibizi@icircles.rw','St Joseph Nyamasheke'),
    ('Nelgan Nijibu','cnijibu@icircles.rw','St Joseph Nyamasheke'),
    ('Alsene Dushimimana','adushimimana@icircles.rw','St Joseph Nyamasheke'),
    ('John Irakoze','jirakoze@icircles.rw','St Joseph Nyamasheke'),
    ('Aime Amani','famani@icircles.rw','St Joseph Nyamasheke'),
    ('Clarisse Mukaniyonkuru','cmukaniyonkuru@icircles.rw','St Joseph Nyamasheke'),
    ('Cynthia Ikirizi','mikirizi@icircles.rw','St Joseph Nyamasheke'),
    ('Radju Muhawenimana','muhawenimana@icircles.rw','St Joseph Nyamasheke'),
    ('Acqueline Kubwimana','akubwimana@icircles.rw','St Joseph Nyamasheke'),
    ('Amos Niyigena','aniyigena@icircles.rw','St Joseph Nyamasheke'),
    ('Esther Uzayikorera','euzayikorera@icircles.rw','St Joseph Nyamasheke'),
    ('Olivier Hakizimana','ohakizimana@icircles.rw','St Joseph Nyamasheke'),

    -- GS Gihundwe
    ('Josee Uwizeye','euwizeye@icircles.rw','GS Gihundwe'),
    ('Austin Morisho','amorisho@icircles.rw','GS Gihundwe'),
    ('James Kwizera','jkwizera@icircles.rw','GS Gihundwe'),
    ('Angelique Ingabire','aingabire@icircles.rw','GS Gihundwe'),
    ('Felix Mukeshimana','fmukeshimana@icircles.rw','GS Gihundwe'),
    ('Rachel Uwimana','ruwimana@icircles.rw','GS Gihundwe'),
    ('Elysee Muyizere','emuyizere@icircles.rw','GS Gihundwe'),
    ('Pacifique Gihozo','gihozopacifique@icircles.rw','GS Gihundwe'),
    ('Celia Giraneza','celiapamella@icircles.rw','GS Gihundwe'),
    ('Aime Nishimwe','jnishimwe2@icircles.rw','GS Gihundwe'),
    ('Venuste Sekabera','vsekabera@icircles.rw','GS Gihundwe'),
    ('Ladouce Irashoboye','pirashoboye@icircles.rw','GS Gihundwe'),
    ('Divine Abayisenga','dabayisenga@icircles.rw','GS Gihundwe'),
    ('Jolie Uwase','juwase@icircles.rw','GS Gihundwe'),
    ('Liliose Umwari','lumwari@icircles.rw','GS Gihundwe'),
    ('Clarisse Uwamahoro','cuwamahoro@icircles.rw','GS Gihundwe'),
    ('Eliane Ishimwe','eishimwe@icircles.rw','GS Gihundwe'),
    ('Eric Mbonimana','embonimana@icircles.rw','GS Gihundwe'),
    ('Delissa Niyigena','dniyigena@icircles.rw','GS Gihundwe'),
    ('Dieu Manzi','dmanzi@icircles.rw','GS Gihundwe'),
    ('Elysee Kwihangana','ekwihangana@icircles.rw','GS Gihundwe'),
    ('Jean Igiraneza','bigiraneza2@icircles.rw','GS Gihundwe'),
    ('Jean Mugwaneza','amugwaneza@icircles.rw','GS Gihundwe'),
    ('Jean Munyakazi','rmunyakazi@icircles.rw','GS Gihundwe'),

    -- GS Mburabuturo
    ('Nillan Inganji','lnillan@icircles.rw','GS Mburabuturo'),
    ('Jacques Tugirimana','tjacques@icircles.rw','GS Mburabuturo'),
    ('Fabrice Iradukunda','ifabrice@icircles.rw','GS Mburabuturo'),
    ('Samuella Uwikunda','usamuella@icircles.rw','GS Mburabuturo'),
    ('Igiraneza Elvis','eigiraneza@icircles.rw','GS Mburabuturo'),
    ('Edison Rukundo','redison@icircles.rw','GS Mburabuturo'),
    ('Nsengiyumva Sedjidi','snsengiyumva@icircles.rw','GS Mburabuturo'),
    ('Agape Tuyisenge','tagape@icircles.rw','GS Mburabuturo'),
    ('Hussuman Karenzi','khussuman@icircles.rw','GS Mburabuturo'),
    ('Gisubizo Kevin','kgisubizo@icircles.rw','GS Mburabuturo'),
    ('Dushime Ezra','edushime@icircles.rw','GS Mburabuturo'),
    ('Christa Izere','ichrista@icircles.rw','GS Mburabuturo'),
    ('Tuyishimire Rehema','rtuyishimire@icircles.rw','GS Mburabuturo'),
    ('Kenny Shema','skenny@icircles.rw','GS Mburabuturo'),
    ('Kenny Irakoze','ikenny@icircles.rw','GS Mburabuturo')
) AS s(full_name, email, site_name)
LEFT JOIN sites ON sites.name = s.site_name
ORDER BY s.email
ON CONFLICT (email) DO UPDATE
  SET full_name = EXCLUDED.full_name,
      school    = EXCLUDED.school,
      site_id   = EXCLUDED.site_id;

-- ROLLBACK:
-- DELETE FROM students WHERE email LIKE '%@icircles.rw';
